### ISSUE TITLE
Keyboard is unselectable in settings

### ISSUE THREAD

**Issue by mnmean** [ColemakMods/mod-dh#11]
This probably isn't an issue with this apk, but maybe you can help. 

I followed the steps: 

Connect a keyboard to the Android device.
Go to Settings > Language & Input.
Find "Physical keyboard" in the list. Selecting this option will bring up a list of currently enabled keyboards.
Select "Set up Keyboard Layouts" to add more layouts.

I can't select the keyboard I'm using (iclever). I have a list of several other keyboards which are selectable (and also not physical at all) which I can change the  layouts (including to colemak-dh). If I unplug the iclever keyboard, the keyboard list completely disappears. So it seems like I can't select it if it's plugged in, and it ceases to exist if I turn it off. 

Here's an image of the screen where the iclever keyboard is unselectable. 
https://i.imgur.com/cPt3L2m.png

The iclever keyboard is listed in a heading font, which is suspicious . . .

Specs: Moto G5+ running Android 7.0

Thanks for any assistance / redirection.

**Comment by mnmean** [comment]
OK. This was my mistake. I didn't realize the physical keyboard is linked to the software keyboards. Carry on, gentlemen.

**Comment by stevep99** [comment]
OK Cool... I didn't get a chance to take a look at this, so I'm glad you figured it out in the meantime :P
