### ISSUE TITLE
Add Italian language on layout analyzer

### ISSUE THREAD

**Issue by finex** [ColemakMods/mod-dh#15]
Hi, on the layout analyzer you can switch between many languages, would be possible to add Italian language too? Thanks!

**Comment by stevep99** [comment]
My source for data is http://practicalcryptography.com/cryptanalysis/letter-frequencies-various-languages/

Unfortunately they don't seem to have Italian listed at the moment.

I'd be happy to add Italian if I had access to a good source for the letter and bigram frequency data.

**Comment by stevep99** [comment]
Just a simple two column list with item and frequency. For examples see the monogram and bigram frequency files for the other languages
