### ISSUE TITLE
Would be possible to add the ñ as AltGr+n?

### ISSUE THREAD

**Issue by 0sk4rgp** [ColemakMods/mod-dh#17]
Would be possible to add the  ñ as AltGr+n? I have no issue with the accents  (á é í ó ú ) just missing the ñ (or what is the shorcut if already exists?)

**Comment by stevep99** [comment]
What are you using - the AutoHotKey scripts, the KLC files, the windows exe?

The unicode values for ñ and Ñ are 00D1 and 00F1, which are defined in the KLC files, for example see in https://github.com/ColemakMods/mod-dh/blob/master/klc/moddh-ansi-us-alt.klc

I am not using Windows at the moment so I can't test it. One option would be to install Microsoft Keyboard Layout Creator, import the KLC file, and try it out. 

If you are using the AHK files, it is somewhat easier, just edit the file to add the mapping.
