### ISSUE TITLE
I can't build the matrix layout in Microsoft KLC 1.4

### ISSUE THREAD

**Issue by finkSpell** [ColemakMods/mod-dh#18]
There are many warnings, which I ignored, but three errors, which I don't understand.
[KeyboardVerify.log](https://github.com/ColemakMods/mod-dh/files/3306751/KeyboardVerify.log)
![2019-06-19 08_19_39-Standard output information](https://user-images.githubusercontent.com/12615121/59778375-35022600-926b-11e9-9319-e89a9825365c.png)

**Comment by stevep99** [comment]
I just tried to reproduce this, using Microsoft KLC 1.4 on Windows 10. 

I also got the long list of warnings you mention (relating to unicode characters), but did not get any errors. The exe files were created, and when running them, the Colemak-DH matrix layout was seemingly correctly added to the system. 

I'm not sure why my experience was different from yours. Mind you, I don't generally use Windows and am not expert on KLC or how it generates layouts. Sorry that's not much help. 

You could try seeing if you get the same error for the ANSI layout file, and if not, using that as base instead (the KLC files are easy to edit). Also, TBH, unless you have a specific reason to use KLC, I'd generally recommend PKL or AutoHotkey-based solutions as these are more flexible and configurable.

**Comment by DreymaR** [comment]
To me that looks more like a run problem than a layout file problem? Maybe there's some virus software interfering?

To test that, you could try importing a standard layout into MSKLC by selecting File > Load existing layout... and saving it as a .klc file that you then load and compile. Just check that it compiles okay, I wouldn't install the resulting layout.  ¯\_(ツ)_/¯
