### ISSUE TITLE
Possible to do Curl-DH without angle mod?

### ISSUE THREAD

**Issue by gnomeria** [ColemakMods/mod-dh#22]
I was having difficulty in using this mod, because if I want the **D** swap with putting **Z** to middle column, it needs the angle mod.
I'm using ANSI keyboard and by modifying the model, it affects my normal qwerty layout.
How to do the move of frequent keys from middle column to the Curl-DH mod? I want to dynamically switch layout based on keyboard layout list.
Thank you.

**Comment by stevep99** [comment]
Yes, the "angle mod" is integral to the design, as if you are use middle finger for C (which is supposedly the correct finger in both Qwerty and Colemak), then it's much easier if it the bottom-left keys move one space to the left.

I'm not sure what you mean by affecting the Qwerty layout. Which method are you using to set the layout?

**Comment by gnomeria** [comment]
I was using 104-curl, but I also want to have the keyboard to be able to switch back to qwerty by pressing ctrl+super+space. But now in even us standard qwerty mode, by left bottom row has been switched, and the **B** key is missing instead in qwerty layout.
Is it possible to have the colemak bottom row switch just like another flavor of US english?

**Comment by DreymaR** [comment]
What SteveP means is that you're not stating even which OS you use nor what implementation for that OS you're employing. From the sound of it, you're on a Linux distro using my XKB files (DreymaR's Big Bag of Kbd Trix) since you're talking about models affecting other layouts. If so, then yes – the keyboard model is separate from the layout so if you just set the layout the model won't change. What I'd do in this case is use a script that sets both model and layout, like my setxkb.sh does. You can bind a hotkey to this.

**Comment by gnomeria** [comment]
My bad on not stating the correct OS. Yes I use Ubuntu 18.04 OS with XKB files in your Big Bag of Kbd Tricks. I guess using the `setxkb.sh` with hotkey would work. But how'd you say making a new layout without using the model configs for the keys on the aforementioned layout? Would that be a huge thing in effort size? Or for example if you could point on how could I do it myself for this or help on this repo?
Is that something that said about not modular yet @DreymaR ?

My assumption would be clone the current layout, and switch keys to match based on the model configs. I actually not really familiar with this.
Thanks

**Comment by stevep99** [comment]
Ah yes, then it does belong in DreymaR's big bag project really, or alternatively just posting on the Colemak forum or discord. I'll leave it open for now in case DreymaR wants to answer here.

**Comment by DreymaR** [comment]
Let's not spam down this repo's issues with my issues. I won't say any more here, except that you can read about how this works in the setxkb.sh script and the BigBag for XKB. ;-)
