### ISSUE TITLE
Cannot switch to Colemak DHm while in Safari on macOS

### ISSUE THREAD

**Issue by maiwald** [ColemakMods/mod-dh#24]
Hi, first of all thanks for these resources! I'm learning Colemak DHm and really like it so far. 😊 

I have a problem with the keyboard layout on macOS Catalina. Whenever I switch to Safari, the selected keyboard layout switches away from Colemak DHm. And while in Safari I cannot switch back to it. In Chrome it works fine.

![Screen Recording 2020-09-15 at 10 56 50](https://user-images.githubusercontent.com/355026/93189570-9355d700-f742-11ea-9d24-84945dcee18c.gif)

Do you have any idea what causes this or where I could look for errors messages? I looked at the console when switching layouts but nothing showed up that looked related.

Thanks!

**Comment by stevep99** [comment]
Hi, sorry to not be much help here - I don't know a lot about how mac-OS handles keyboard layouts. The mac DHm configuration was contributed by @njdoyle , I don't know if he would have any input on this?

**Comment by maiwald** [comment]
Thanks for the reply! I just found https://superuser.com/questions/665494/how-to-make-a-custom-keyboard-layout-in-os-x and moved the layout bundle into `/Library/Keyboard Layouts/` instead of `~/Library/Keyboard Layouts/`. It works fine now.
