### ISSUE TITLE
Android layouts with multilingual layer and caps -> backspace

### ISSUE THREAD

**Issue by calin-darie** [ColemakMods/mod-dh#25]
You may copy over these layouts or simply link to them:
https://github.com/varzan/extra-keyboard-layouts/blob/master/app/src/main/res/raw/keyboard_layout_colemak.kcm
https://github.com/varzan/extra-keyboard-layouts/blob/master/app/src/main/res/raw/keyboard_layout_colemak_mod_dh.kcm

**Comment by calin-darie** [comment]
I'm not sure you need separate layouts for non-wide keyboards. I think the layouts I provide will always work. Only for certain keyboards certain mappings will never be used.

**Comment by stevep99** [comment]
Thanks for this contribution. I noticed that your mod_dh file varies from the standard, as the bottom row isn't applying the angle mod. But do I think your multilingual additions are a good feature, and would be worthwhile to support. So what I have done is added your multilingual mappings to the existing mapping files.

**Comment by calin-darie** [comment]
Fixed: applied angle mod. Thanks for pointing that out!

**Comment by calin-darie** [comment]
And scratch my previous comment about wide: I thought it was for some limited keyboard, but turns out it's an extra mod.
