### ISSUE TITLE
Would you be able to add the Finnish language in the keyboard analysis tool?

### ISSUE THREAD

**Issue by Vakke** [ColemakMods/mod-dh#26]
Hello!

From the data site you use there's a Finnish language also. Would you be able to implement it to the analysis tool aswell? I would be extremely interested to find out the results as the Colemak and Colemak DH both have J in the same place. Letter J is often used in Finnish and is the first letter in our most used word "ja" which means and. 

As the J is in the same position as Y in QWERTY it feels that the position might not be the most ideal in Finnish but I think the analysis tool is much better in determining that than I am!

Hopefully you would be able to do that and I'm forever grateful!

**Comment by stevep99** [comment]
Hi there,
Yes, I have just added Finnish.

According to that data, J appears 2.1% in Finnish, which is more than in English but still not extremely common. 

But I agree that Qwerty Y position is bad. Maybe if you type more Finnish than English, you could do a small adjustment, e.g. switching J with W (I notice W seems to be rare in Finnish). Anyway, Finnish is supported now, so you can experiment!

Steve

**Comment by DreymaR** [comment]
The situation is similar to Dutch which also uses J a lot. We still couldn't determine a better place for it using the DH-mod principle, as the other right-hand index letters (L KN MH) still outranked J even in Dutch. If Finnish has J outplaying any of those letters, I'd suggest a swap with the losing part. Otherwise, I'd leave it be if you're typing any amount of English too.

**Comment by stevep99** [comment]
Just an observation: Finnish users seemingly need a strong right index finger:

**Top Same-Finger Bigrams**
finger 6 | NK | 0.861%
finger 6 | NJ | 0.403%
finger 6 | NM | 0.386%
finger 6 | NL | 0.267%
finger 6 | LM | 0.228

**Comment by Vakke** [comment]
> Just an observation: Finnish users seemingly need a strong right index finger:
> 
> **Top Same-Finger Bigrams**
> finger 6 | NK | 0.861%
> finger 6 | NJ | 0.403%
> finger 6 | NM | 0.386%
> finger 6 | NL | 0.267%
> finger 6 | LM | 0.228%

That is actually something I've been thinking too :D Fortunately over a half I type is in English so it might be worth to try Colemak DH, and also, the experience with it might be the only thing that determines that is the right index finger good enough for the job!

**Comment by Vakke** [comment]
> The situation is similar to Dutch which also uses J a lot. We still couldn't determine a better place for it using the DH-mod principle, as the other right-hand index letters (L KN MH) still outranked J even in Dutch. If Finnish has J outplaying any of those letters, I'd suggest a swap with the losing part. Otherwise, I'd leave it be if you're typing any amount of English too.

I read the discussion you had with the people in Colemak forums and I think it might just be better to be left alone as you said. I'm not capable of doing my own layout which might be the best one for Finnish and English and I think if I could there wouldn't be any other to take advantage of it :D

**Comment by Vakke** [comment]
And also thank you a ton for adding Finnish there!

**Comment by DreymaR** [comment]
I strongly recommend using alt-fingering for such bigrams! It's easy to let the middle finger handle N in NK/KN, NM/MN, NJ/JN which takes care of the most common ones. In my experience this has nearly no adverse effect on continuing with other letters, but you need to learn to not be too fixed in your position – which is good for typing fast anyway. NL/LN is more tricky, For LM/ML I let the middle finger type L, as is the case for LK/KL.

**Comment by Vakke** [comment]
> I strongly recommend using alt-fingering for such bigrams! It's easy to let the middle finger handle N in NK/KN, NM/MN, NJ/JN which takes care of the most common ones. In my experience this has nearly no adverse effect on continuing with other letters, but you need to learn to not be too fixed in your position – which is good for typing fast anyway. NL/LN is more tricky, For LM/ML I let the middle finger type L, as is the case for LK/KL.

That is a very good idea and something I have to implement. My last and only concern still is the heave usage of right hand in Finnish with Colemak DH and normal variants. When using the software calculations with added ä, ö and å, it seems that right hand should handle almost 62 percent of writing. With QWERTY it is around 55 percent for the right hand so the jump of usage is there but it shouldn't be that big of a deal I think.

Do you have same estimations or experience with your native language? I think by experimenting I'll only find out how it works for me atm.

**Comment by DreymaR** [comment]
What I do is use a Wide/Angle mod to keep the æøå in the middle of the board. So I mostly use the left hand index finger for those letters. The Wide mod generally takes load off the right hand pinky which is good. Also, using Extend means I press Backspace from the home row and Enter with my thumb which helps further.

In general, Colemak was designed to not move many keys between hands and I agree with that principle. It's also hard to change anything without breaking something, as it's so well optimized. So I'd think long and hard before I tried to swap any keys between hands or fingers.
