### ISSUE TITLE
Prebuilt Windows ANSI zip is still DHk

### ISSUE THREAD

**Issue by rtrajano** [ColemakMods/mod-dh#29]
I installed this and found the keys for m and k are swapped.

Steps to reproduce:
1. click the link on the Windows readme for the ANSI zip.
2. install and set as current layout.
3. type m and k.

**Comment by stevep99** [comment]
Hi, thanks for the report. 

I'll get this fixed in the next few days. Is it referring to the installer in the "colemak_dh_ansi_us.zip" file? 

In the meantime, the KLC file looks to be right, so you should be able to regenerate the correct installer using Keyboard Layout Creator.

**Comment by stevep99** [comment]
OK, so I have tested all 3 of the ANSI variants on a fresh windows install, and all of them seem to have the correct mapping (M in the middle row). Can you double-check, make sure you don't have an old DHk variant being used by mistake.

**Comment by rtrajano** [comment]
I reinstalled today and it's DHm. Odd... Maybe I installed it on the cusp of the change. All good now, thanks.

**Comment by stevep99** [comment]
One thing I realized is that the old (DHk) files were just renamed but if you installed, the internal name still Colemak-DH instead of Colemak-DHk. This might have lead to possible confusion also. 

So just to be sure, I have just updated the installers with the correct names.
