### ISSUE TITLE
Mod-dh and the updated mod-dhm style

### ISSUE THREAD

**Issue by pawelurbanski** [ColemakMods/mod-dh#30]
Hello,
I would like to confirm if the AutoHotkey and possibly the Windows KLC executables are created according to the recent change?
According to the post at the Colemak website, the DH mode will integrate the following:
1. Colemac-DHM style bindings,
2. The 'M' keya the home row,
3. The 'K' key in the bottom row,

Any hints will be appriciated... I would like to create the Kinesis Advantage 2 mapping file according to the valid layout and contribute it to the repository for I had problems finding a definitive Kinesis layout.

All the best and thanks for your great work.

**Comment by stevep99** [comment]
Yes, all the files have been updated to M in the middle row, K on the bottom row.

For the Kinesis Advantage 2 you should get the "matrix" variant.
