### ISSUE TITLE
On mac, clicking into the slack app reverts the layout to previous

### ISSUE THREAD

**Issue by imh** [ColemakMods/mod-dh#32]
If your last layout was qwerty, it goes back to that, but it will also fall back to the builtin colemak or to the downloadable layout from the workman website if either of those was your last layout, so the issue appears to be with this repo's layout.

macOS 10.15.7
Colemak DH ANSI

**Comment by Jitsusama** [comment]
@imh; I found that if I put the layout in "~/Library/Keyboard Layouts" I experience that issue, but it I put it into "/Library/Keyboard Layouts" it doesn't. This appears to be some issue with certain apps only working with system level layouts while other apps can work with user or system layouts.

**Comment by imh** [comment]
Thanks @Jitsusama! That did it! I'm closing the issue.

**Comment by jonasmerlin** [comment]
Sadly, this didn't solve it for me. I have the layout in "/Library/Keyboard Layouts" but it still switches around and often, I can't switch to the Layout at all. It seems to work when I reinstall it, but once I restart it's broken again and switches around. My guess is that it's got something to do with having "unlocked" the Layouts folder when putting in the files?

**Comment by mikeduminy** [comment]
Same problem here

**Comment by tim-phillips** [comment]
A restart of my computer solved this for me.

**Comment by zeljkobekcic** [comment]
Yes, here too. I tried both locations and reboots, but only `"~/Library/Keyboard Layouts` and a logout helped.
