### ISSUE TITLE
Include RANT layout in comparison list

### ISSUE THREAD

**Issue by NotGate** [ColemakMods/mod-dh#33]
I noticed your comparison page includes lesser-known layouts like Soul and Niro (https://colemakmods.github.io/mod-dh/compare.html). 
Can you include my layout in this table as well? It scores better than MTGAP and Colemak by focusing on SFB count. 

![image](https://user-images.githubusercontent.com/32425311/104612724-20a32c80-564c-11eb-86ef-475280c98184.png)

```
;    ,    h    m    z    b    f    o    u    x
r    a    n    t    j    g    w    e    i    s
'    .    l    d    k    p    c    q    y    v

1    2    3    4    5    6    7    8    9    0    -    =
;    ,    h    m    z    b    f    o    u    x    [    ]
r    a    n    t    j    g    w    e    i    s    /
'    .    l    d    k    p    c    q    y    v
```

**Comment by stevep99** [comment]
Looks to be a decent layout. There are increasingly a lot of layouts that people make though. I should come up with some sort of criteria for what to include otherwise things will get out of hand. Certainly any that start to get substantial user base I'll include.

**Comment by DreymaR** [comment]
RANT and ISRT/IndyRad are about the same: Mostly based on an SFB minimizing. I wouldn't see the need to include everything that moves. In fact, I'd remove Soul and Niro from the battery to avoid questions like this. For the fans of a layout it should be easy enough to just add it manually?

One cool feature would be the ability to import a layout from a JSON or similar file. How about that? Then all these "oddball" layouts can have such a file somewhere for downloading. ISRT/IndyRad has its own page at least; maybe that should be a mimimum criterium for adding a layout?  (❁°‿°)
