### ISSUE TITLE
ANSI vs ISO confusion

### ISSUE THREAD

**Issue by quangv** [ColemakMods/mod-dh#39]
I got so confused looking at the keyboard layout images on the homepage...

Didn't know which keyboard I had, ANSI, ISO, staggered, matrix or ergo?!

It wasn't clear to me till I downloaded "Microsoft Keyboard Layout Creator" and loaded Colemak.

![keyboard](https://user-images.githubusercontent.com/1171187/112417561-44df5180-8cfe-11eb-916f-a1de22378e3f.PNG)

Oh! that key after the left shift is _might not be present on all keyboards_ k things makes more sense!

I'm not sure how best to call this out on the DL page?

p.s.:
(still doesn't explain why on macOS had to use colemak-dh--matrix to get the ZXCDV to line up correctly though, different issue for another day)

Edited: Actually on windows after installing the ANSI keyboard layout from the zip file... the last row doesn't seem quite right.

Expected (after the left shift key): ZXCDV
Actual: XCDVZ

Same thing was happening on my macOS and i resolved it by using the matrix layout. Was able to resolve this on Windows too by installing the matrix layout.

----

**Update**: crap I think I had ANSI keyboard the whole time... so the bottom row should be XCDVZ 🤦‍♂️

**Comment by stevep99** [comment]
Correct. if you don't have that extra key between Z and left-shift, then you have an ANSI board, in which case your bottom row should be XCDVZ. Make sure you hit C with middle finger and D with index finger.
