### ISSUE TITLE
What is the difference between the regular and extended version of the layout?

### ISSUE THREAD

**Issue by Nostravinci** [ColemakMods/mod-dh#41]
Hello,

I am using a MacBook Pro with a Apple Magic Keyboard (soon to move to a Moonlander).

I believe that the Colemak DH Ansi layout is the correct one to use (please tell me if I am wrong).

What is the difference between the regular and extended version of the layout?

Thanks!

**Comment by njdoyle** [comment]
The "Extended" layouts mirror the functionality of the builtin "ABC - Extended" layout (versus the plain "ABC" layout). The main difference is in the way you type special or accented characters. Some further reading here: https://sites.psu.edu/symbolcodes/mac/codemacext/

If your "Return" key is shaped like an upside-down L then you want to use an ISO layout. If your "Return" key is just a rectangle, you want to use an ANSI layout. If your keys are in a grid (like the Moonlander), you want to use a Matrix layout. The Moonlander is programmable, though, so it's generally best to just program Colemak-DH right in to the keyboard; that's what I do with my Corne keyboards.

**Comment by Nostravinci** [comment]
Excellent answer—thank you so much!

**Comment by DreymaR** [comment]
The Return key is in fact not a safe-fire way to decide your keyboard type, as there are several ANSI boards with different Return key form factors. The safest indicator is the extra ISO key between Z and Left Shift. If a board has that one, it's an ISO keyboard – in addition, ISO keyboards generally have a key between the apostrophe key and Enter. ANSI keyboards don't have an ISO key, obviously. There are also other variants, like ABNT and JIS, but people who have those boards usually know it.
