### ISSUE TITLE
Are there some page-long diagrams of the DHK layout?

### ISSUE THREAD

**Issue by ghost** [ColemakMods/mod-dh#46]
Hi,

Over here

https://colemakmods.github.io/mod-dh/keyboards.html

, there are small prints of the different keyboard layouts.  Same thing, across the web.

But are there any we can download or purchase, that would take up an entire lanscape letter page, that we can hang on the wall?

**Comment by DreymaR** [comment]
Not sure why you'd require quite so high resolution. But you could make such a diagram with EPKL. Out of the box it supports mainly the standard DH now (DHm) but there are still DHk images for some of the mod combos you could use.

The result will look like this, or you could use another background. You can increase the image size a lot to get more pixels.
![https://raw.githubusercontent.com/DreymaR/BigBagKbdTrixPKL/master/Layouts/Colemak/Colemak-ISO-CAWS_s0_EPKL.png](url)

**Comment by stevep99** [comment]
Another option is you could generate some the tool I made for this
https://play.google.com/store/apps/details?id=io.github.colemakmods.keyboard_companion

However they aren't particularly big by default - if you're OK with a bit of coding you could adjust the settings & background images to make them huge.
