### ISSUE TITLE
Add support to lower quotation marks

### ISSUE THREAD

**Issue by GrimPixel** [ColemakMods/mod-dh#47]
This is a long unresolved issue. Some languages require them but it's not present in Colemak, and not in this version as well.

https://wikiless.org/wiki/Quotation_mark?lang=en#Summary_table

My own modification is getting rid of × and ÷ to make room for „ and ‚

**Comment by DreymaR** [comment]
They are present in Colemak[eD], my preferred AltGr and dead key mappings for Colemak and other layouts. If you're on Windows you can get it either with the EPKL program or a MSKLC install (only for Colemak-CAWS by default, but editable).

 ( Θώθ)  ～(  See "DreymaR's Big Bag Of Keyboard Tricks"  )
   https://dreymar.colemak.org

**Comment by stevep99** [comment]
There are a wide variety of additional languages, symbols and characters that can be supported, but I'd say this is out of scope of the base layout definition. 

Different implementations can provide customised layouts targeted for different preferences (language and/or symbols), and DreymaR's is the go-to example for internationalization, and is linked to in the Downloads section.

**Comment by GrimPixel** [comment]
Yeah, there are a lot of languages, but even European languages like German can't be supported for the very commonly used quotation marks, how do we expect common users to use it?

**Comment by DreymaR** [comment]
As I said: The BigBag does contain all that. So use it. Please. It does solve your problems.

**Comment by GrimPixel** [comment]
My problem is solved by directly editing the files at /usr/share/X11/. Common German, Polish and other language users that don't play with so much configuration still have that. What they need is a keyboard layout that natively has the quotation marks that they use every day. Otherwise you can even say your keyboard supports any writing system.
