### ISSUE TITLE
Add download instructions to the installation README file (MacOS)

### ISSUE THREAD

**Issue by JerriAtric** [ColemakMods/mod-dh#50]
As a Mac user unfamiliar with GitHub, I want to know how to *download* and install the package. 

The README.md file tells me how to copy the "Colemak DH.bundle" file into the appropriate folder on my Mac. But it doesn't tell me how to download it from github, and this isn't obvious. Especially from the [MacOS page](https://github.com/ColemakMods/mod-dh/tree/master/macOS). 

After clicking around for a while I realized I could go back up to the [main page](https://github.com/ColemakMods/mod-dh) and use the "Code" button to download the entire package, and then go in and find the MacOS components I needed from there. 

I think that should be added to the README.md file.

**Comment by muppetjones** [comment]
Ideally, an archive could be created using github actions.

**Comment by stevep99** [comment]
Thanks for the suggestion, fixed.
