### ISSUE TITLE
Update the iso layout for international support

### ISSUE THREAD

**Issue by DanielFabian** [ColemakMods/mod-dh#51]
I just saw that the US matrix layout has international KLC files. But the ISO version (https://github.com/ColemakMods/mod-dh/blob/master/klc/colemak_dh_iso_uk.klc) does not.

Would it be possible to update it please to support the multilingual dead keys?

**Comment by stevep99** [comment]
Not sure why this is the case, but seems an oversight - added to TO DO list.

**Comment by DreymaR** [comment]
A little tip: My EPKL program holds a lot of dead keys for those who want even better international support. I only included the CAWS mod combo, but anyone with a little savoir faire can easily edit the key scan codes in the .klc file.

**Comment by stevep99** [comment]
I have regenerated the KLC files using the official (default) Colemak KLC file as a base, so the international deadkey mappings should be inherited from there for all variants.
