### ISSUE TITLE
Add setxkbmap command to README

### ISSUE THREAD

**Issue by abhidg** [ColemakMods/mod-dh#52]
Colemak DH is now in xkeyboard-config (at least as of 2.34), so one can do

     setxkbmap us -variant colemak_dh

There is a colemak_dh_iso option as well!

**Comment by stevep99** [comment]
Good point, now done.

**Comment by DreymaR** [comment]
I think that `setxkbmap "us,colemak_dh"` works the same as the above command, fwiw
