### ISSUE TITLE
Windows 10 shortcut issues

### ISSUE THREAD

**Issue by andrewmartin5** [ColemakMods/mod-dh#57]
I have installed the dh swap ansi version with klc, but the locations of keyboard shortcuts have changed to reflect the colemak locations. Is there a way to use standard qwerty keyboard shortcuts?

**Comment by DreymaR** [comment]
EPKL supports VK codes and you could trick Windows with it, but as SteveP says it isn't the best of ideas. Just learn the proper positions for the shortcuts! They're mostly mnemonic anyway, not positional.

For some shortctuts like Cut/Copy/Paste, there is definitely an element of position in their usage. Even so, I elected to let Ctrl+V follow the V key in the CurlAngle mod in Colemak-DH – as is the standard. If that dilemma bothers you, you may for instance use an Extend or dead key layer with the old key positions if you're on EPKL (DK layers are supported by KLC as well).
