### ISSUE TITLE
 Ive installed mod-dh/klc/colemak_dh_matrix_us.zip, it overwrote my other layouts and I cant reset them back

### ISSUE THREAD

**Issue by lazazael** [ColemakMods/mod-dh#63]
Im on win11, installed this layout
every time I try to install a new layout or language pack, every keyboard layout under my user defaults to this and only changes some characters but not all, the 3 main rows stay the same but the perimeters change its really weird
Ive tried reinstalling the default layouts from microsoft layout creator but it didnt help
also tried to delete the dll coming from this installer with no luck either
how to reset back to the original layouts?
now I got only 1 language pack installed, 1 layout and its still colemak_dh_matrix from a to o, q to ; etc. other keys are normal
even if I install a new layout with the custom keyboard tool or anyhow it keeps the basics of colemak
thanks in advance

**Comment by DreymaR** [comment]
Did you restart after installing? It's vital that you do.

You need to deactivate the layout, then uninstall it. See the Other\MSKLC folder of my EPKL program for more info.
https://github.com/DreymaR/BigBagKbdTrixPKL

**Comment by lazazael** [comment]
Ive restarted several times for now, lately when I deleted everything, kept the only default language pack installed with 1 single layout. This is what I need to reset to default.

**Comment by lazazael** [comment]
im back on track
so Ive installed a 3rd language pack, deleted a the previous ones, restart, than installed the previous 2 and deleted the 3rd temporary and it solved my problems
