### ISSUE TITLE
Moonlander

### ISSUE THREAD

**Issue by jakobneufeld** [ColemakMods/mod-dh#64]
I am buying a Moonlander Ergonomic keyboard, and I was curious if for ergonomic keyboards, ColemakDHk, or  ColemalDHm is "better". For me, the main aim is to have the most ergonomic and comfortable layout not the fastest.

Thanks in advance to anyone who replies

**Comment by stevep99** [comment]
Definitely Colemak-DHm (which is the standard Colemak-DH) is the right one to use.

**Comment by DreymaR** [comment]
There is really only one standard now, it's DH (which equals DHm).

https://www.colemak.org

**Comment by jakobneufeld** [comment]
Thanks!

**Comment by iamursky** [comment]
I found it uncomfortable to press <kbd>K</kbd> and <kbd>V</kbd> on Moonlander Mark I with my index fingers. It was easier to press them with the big ones, but instead I moved these keys to the right column where <kbd>/</kbd> and <kbd>?</kbd> originally are.

<img width="661" alt="Screenshot 2022-12-14 at 19 27 02" src="https://user-images.githubusercontent.com/33891482/207679467-5cf970c1-8ae8-4616-9cac-23f9993e61bf.png">

**Comment by jakobneufeld** [comment]
I will try that out!

**Comment by iamursky** [comment]
I'm making a typing trainer with support of this layout, you can try it out here: https://www.typing.men

**Comment by DreymaR** [comment]
Ooo, I really wouldn't recommend that. Colemak has fairly common letters (A and O) on pinkies, but nothing that creates frequent same-finger bigrams with them. The pinky has no big problems pressing those keys, but jumping up and down for SFBs is another matter entirely. Nope, I would not do that.

**Comment by iamursky** [comment]
@DreymaR, what do you thing of placing K and V under E and I (HKV)?

**Comment by DreymaR** [comment]
> @DreymaR, what do you thing about placing K and V under E and I (HKV)?

 ¯\_(ツ)_/¯
