### ISSUE TITLE
Links to Microsoft Keyboard Layout Creator (KLC) are no longer valid

### ISSUE THREAD

**Issue by VeH-c** [ColemakMods/mod-dh#66]
Please update all instances of `http://msdn.microsoft.com/en-GB/goglobal/bb964665.aspx` with one of the following 

- https://www.microsoft.com/en-us/download/details.aspx?id=102134 
- https://web.archive.org/web/20160503155530/https://msdn.microsoft.com/en-gb/goglobal/bb964665.aspx 
- https://archive.org/details/MSKLC
- https://www.softpedia.com/get/System/OS-Enhancements/Microsoft-Keyboard-Layout-Creator.shtml
Also, it's called Microsoft Keyboard Layout Creator (MSKLC)

**Comment by stevep99** [comment]
Thanks, have done with the first option.
