### ISSUE TITLE
Colemak DH Mac OS works only in Safari

### ISSUE THREAD

**Issue by zelds** [ColemakMods/mod-dh#67]
Hi. Does any one else reported problem that layout (Colemak DH matrix) works only in Safari ? Like I try to switch it using select in top bar, but changes are not applied. Looks like Mac OS bug, but maybe some one found any solution for that ?
I try use it in different terminals with no luck.

**Comment by hansamann** [comment]
it also did not work for me... back to regular colemak

**Comment by blwinters** [comment]
Changing those values in the `.keylayout` file worked for me. Perhaps there's either a conflict or one of the values is invalid. I did notice that the `id` was a negative number, not at all sure if that's a problem though.
