### ISSUE TITLE
Using colemak-dh on the Remarkable 2 Type Folio

### ISSUE THREAD

**Issue by mkborregaard** [ColemakMods/mod-dh#68]
Hi,
I read that I need a "qmap" file of my keyboard layout to use it in a Qt application. Is a qmap file of this layout available?
Thanks!

**Comment by stevep99** [comment]
I'm not familiar with qmap files, but I would say you should be setting your layout at the OS level. I don't think anything Qt-specific would be relevant.

**Comment by mkborregaard** [comment]
Just to give context to the question: This is for the "remarkable", a paper tablet with an attachable keyboard, and my information is given under 6.1 here https://benkku.medium.com/the-remarkable-2-tablet-as-a-coding-writing-device-3981570343e2

So I can't really do anything on the OS level. But I honestly had never heard of qmaps either :-)

I just bought the device, then remembered that I've been using mod-dh for a small decade and have no chance of ever using a qwerty keyboard anymore :-D

**Comment by DreymaR** [comment]
I just have to wave to you, Michael! Long time, no see!  ( のvの) c[_]

(For any other readers: This is the guy who masterfully implemented my Big Bag of Kbd Tricks for Mac, years ago.)

**Comment by stevep99** [comment]
Oh, I haven't seen such a device before. 
I guess you may have seen [this](https://github.com/dps/remarkable-keywriter/issues/1l) already?
Sounds like the best would be for the vendor to provide more info on this, then it ought to be pretty easy to adjust an existing layout definition.

The other option - and the one I would most recommend - would be to get a programmable keyboard or a USB remapper device. The latter is a good option if you already have a keyboard you want to use. It takes away all the pain of having configuring software.

**Comment by mkborregaard** [comment]
Yeah the Remarkable is amazing, it's a non-backlit e-reader and writer device that feels really deceptively like paper. 

Keywriter, which you link to, is a hack to associate an external keyboard to the remarkable - but now the device itself can come with a small inbuilt keyboard instead, and that's the one I have bought and now want to remap. 

I contacted company support and they said it's not possible to remap keys at this point but they would take a feature request. However the device is open source, and the keymapping is hardcoded into the kernel, so I'm considering if I'm adventurous enough to recompile the kernel and replace it...

**Comment by mkborregaard** [comment]
Alright, someone (@Eeems) on the Remarkable forum gave me an incredible amount of help, and I managed to make my type folio work for the remarkable. It requires a bit of fiddling. Essentially I needed to edit the keyboard driver of the remarkable's operating system (which is [open source](https://github.com/reMarkable/linux)), then use a docker container with linux and the entire remarkable toolchain preloaded (which @Eeems was kind enough to prepare). In the docker container I download my updated driver, recompile the kernel, then use ssh (scp) to copy the new driver to the device. And it works!

Here are the steps if anyone should be adventurous enough:

### Instructions

Install docker first. Then:
```
docker pull eeems/remarkable-toolchain:latest
docker run -ti eeems/remarkable-toolchain:latest
```
In the docker session, type:
```
git clone https://github.com/mkborregaard/remarkable_linux_colemak_dh.git
cd linux
git checkout colemak
source /opt/codex/rm11x/3.1.15/environment-setup-cortexa7hf-neon-remarkable-linux-gnueabi
make mrproper
touch .scmversion
cp arch/arm/configs/zero-sugar_defconfig .config
make olddefconfig
make drivers/misc/rm-pogo/pogo.ko
make modules_prepare
```
Then, in a normal terminal, first get `**container_name**` by typing:
```
docker ps
```
then use that to copy the `pogo.ko` file to your host system.
```
docker cp **container_name**:/root/linux/drivers/misc/rm-pogo/pogo.ko .
```
Then connect the remarkable and make an ssh connection. In a normal terminal, type:
```
scp pogo.ko root@10.11.99.1:/lib/modules/5.4.70-v1.3.3-rm11x/kernel/drivers/misc/rm-pogo
```
Disconnect remarkable, restart it, and connect to the type folio

**Comment by mkborregaard** [comment]
I should add that I use a slightly out-of-date version of the layout where k and m are swapped. If anyone is interested I'm happy to edit and provide a proper one.

**Comment by mkborregaard** [comment]
Should we close the issue or what works best?

**Comment by NQNStudios** [comment]
@mkborregaard  Using these instructions and your fork as an example, I was able to do this for dvorak: https://github.com/nqnstudios/remarkable_dvorak

So thanks!

**Comment by alphashuro** [comment]
@mkborregaard thanks for this info! I also managed to use your instructions and a diff of your fork to do this for the not-outdated version of mod-dh here https://github.com/alphashuro/remarkable-linux-kernel/tree/colemak-dh

I also summarised your instructions with some changes to make it work for the current version [here](https://gist.github.com/alphashuro/3aa5b67309e974542b9ee59f19079755)

**Comment by mkborregaard** [comment]
@alphashuro amazing, thank you for doing this!
