### ISSUE TITLE
Proposal: Swap V and K

### ISSUE THREAD

**Issue by EnricoGhiorzi** [ColemakMods/mod-dh#70]
Looking at the results from the analysis tool (Layout: Colemak-DH, Configuration: Ergonomic), it appears one of the most common same-finger bigram is KN:

finger 6 | KN | 0.105%
-- | -- | --

I tried swapping K with a similarly positioned letter: V. The results are quite good for such a minor change: from the score of Colemak-DH on an Ergonomic configuration

total * | 1.670 | 0.052 | 0.013 | 1.735
-- | -- | -- | -- | --

we get

total * | 1.670 | 0.045 | 0.012 | 1.728
-- | -- | -- | -- | --

and similar improvements are obtained on other configurations and on steveP's analyzer (on English text).

Has this mod been proposed before? Is there any chance of it being implemented in Colemak-DH?

**Comment by DreymaR** [comment]
Yes, it's been proposed before. Haven't heard from the Q-Mod gang in quite a while, but it was a hot topic back then.

I even tried out the V–K swap. I didn't like it, for reasons explained in my EPKL layout readme:

https://github.com/DreymaR/BigBagKbdTrixPKL/tree/master/Layouts/Colemak/Cmk-Qmods

**Comment by EnricoGhiorzi** [comment]
Thank you for the info, I was unaware of a lot of recent developements. Some recent analyzers, such as <https://o-x-e-y.github.io/layouts/playground/index.html>, highlight the drawbacks of swapping V and K. I also found sources where the mod is called Colemak DHv and is credited to Oats. I consider this to close the issue.

**Comment by DreymaR** [comment]
Oats' layout is something else iirc, he wanted to type without the Angle mod so he fiddled around a bit. Since Oats is blindingly fast(!) with his layout variant, it's obvious that it isn't bad! But I don't think it's as good as using the Angle mod properly.
