### ISSUE TITLE
inconsistent placement of the equal sign in the wide mod

### ISSUE THREAD

**Issue by BluewyDiamond** [ColemakMods/mod-dh#77]
In the website and xkb the wide mod has the following order: ... 4 5 6 = 7 8 ...
but in the console, autohotkey, klc... It follows this order: ... 4 5 = 6 7 ...

why is it inconsistent? which one is the correct one?

I use both xkb and console layouts, which causes my muscle memory and my brain to be confused and not realize why the password I inputed would not work and would get myself locked out of my system :(.

**Comment by stevep99** [comment]
Well spotted! 

It's really a matter of preference. Some split keyboards have the 6 [on the right](https://matias.ca/ergopro/pc/) and others have it [on the left](https://ultimatehackingkeyboard.com/). Even if you're using a non-split keyboard, it depends on which convention you use to decide where the "split" should be.

The historic reason is that I used to have a Matias Ergo Pro, so I got used to 6 on the right, and made the wide mod files match that convention. I know DreymaR prefers 6 on the left though, and to be fair, 6 on the left is slightly nearer the home row.  The images used to show 6 on the left, I must have updated them at some point. 

I'll have to update the download files to make them consistent with the images, but there is no real "correct", only what you prefer!

**Comment by arlen-kleinsasser** [comment]
similar issue with the / and # on the iso wide mod here:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/442
We are lucky to have 5 DH variants upstream in xkb and while some of it comes to personal preference.  When the layout is getting implemented in other projects an official spec would really help

**Comment by DreymaR** [comment]
I'd say `6 \ 7` is the most official version, yes, and it has been for years.

On a row-staggered board, the left-hand stretch to the 6 key becomes (0.75,2)u and the corresponding right-hand stretch (1.75,2)u which is substantially longer. It makes sense to have the number 6 on the shorter stretch.

Matrix geometry boards usually don't need a Wide mod (or at least have no standard), and row-staggered splits are inconsistent anyway as SteveP pointed out.

Five US English DH variants sounds like too much? There needs to be ISO, ANSI and matrix variants. That's what the standard contains. What other twists have snuck in?

That said, I am hoping my Colemak-eD variants will eventually get a place. Ugh, standardization is impossible.

https://dreymar.colemak.org

**Comment by stevep99** [comment]
Have finally resolved this, the downloadable files are now consistent with the website images.
