### ISSUE TITLE
Keyboard image fingering inconsistency

### ISSUE THREAD

**Issue by DreymaR** [ColemakMods/mod-dh#8]
On your colemakmods [Keyboard types page](http://colemakmods.github.io/mod-dh/keyboards.html), you have the number fingering I like for most of the images, hitting 9 with the middle finger (green) and 0 with the ring finger (magenta). However, on two of the ANSI images that's different for no apparent reason. Hopefully, this is unintended and it would be easily fixed with a little copy-pasting. ;-)

**Comment by stevep99** [comment]
Yes, a couple of the images seem are not right regarding the 9. Well spotted!
