### ISSUE TITLE
Add Android APK to F-Droid

### ISSUE THREAD

**Issue by cal-andrew** [ColemakMods/mod-dh#80]
This would make it much easier to use Colemak-DH on custom ROMs.

**Comment by cal-andrew** [comment]
@stevep99 Do you mind if I get Colemak-DH added to F-Droid?

**Comment by stevep99** [comment]
Sure go ahead!

**Comment by cal-andrew** [comment]
Merge request is here: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15187
