### ISSUE TITLE
Move to Codeberg

### ISSUE THREAD

**Issue by cal-andrew** [ColemakMods/mod-dh#81]
It doesn't have to be Codeberg, but moving the repo to an open source host would be appreciated.
I probably don't have to go over the problems with GitHub...
Thanks for the wide platform support btw! It's really helpful.

**Comment by DreymaR** [comment]
You probably do have to go over the problems with GitHub, as I at least don't know what you're referring to.

**Comment by cal-andrew** [comment]
Here are the problems with GitHub:
- GitHub is proprietary and owned by Microsoft.
- It forces you to make an account to contribute to projects that are on it (as opposed to git itself which allows you to do issues and patches through email).
- Microsoft also trains their AI models on code hosted on GitHub.

Here is more info: https://sfconservancy.org/GiveUpGitHub/

But I closed the issue because I don't want to be telling you what to do for your projects as a random guy.

**Comment by cal-andrew** [comment]
Even GitLab is an improvement on some of these points

**Comment by cal-andrew** [comment]
@stevep99 Do you mind if I mirror this repo to Codeberg?
