### ISSUE TITLE
Update Android APK to latest version

### ISSUE THREAD

**Issue by cal-andrew** [ColemakMods/mod-dh#84]
Hi Steve,
I noticed that the Android APK is at version 1.02 while the latest version in the `build.gradle` file is version 1.03. Would you be able to update it please?

Also, I think the `versionCode` field needs to be updated for every release (https://developer.android.com/studio/publish/versioning)
```diff
diff --git a/android/app/build.gradle b/android/app/build.gradle
index 5ef82ae..551132d 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -10,7 +10,7 @@ android {
         minSdkVersion 16
         targetSdkVersion 33
 
-        versionCode 2
+        versionCode 3
         versionName "1.03"
         setProperty("archivesBaseName", "moddh-$versionName")
     }
```

**Comment by stevep99** [comment]
There weren't actually any differences to the mappings, only the android build script changed.
But for clarity I've put the 1.03 build there now.

**Comment by cal-andrew** [comment]
@stevep99 Thank you so much! One last request, would you be able to tag Android releases to allow the app to be automatically updated in F-Droid?

**Comment by stevep99** [comment]
The problem is there are different kinds of releases for different platforms with each in a subdirectory so I think that will probably confuse things.

**Comment by cal-andrew** [comment]
F-Droid suggested you tag the releases as Android-x.x.x. Would that work?

**Comment by cal-andrew** [comment]
@stevep99 Thanks for your help. While tags aren't required, it would be very quick to do and help a lot.
Here's how it would work:

- `git tag Android-x.x.x` whenever you make a new Android release
- `git push --tags`

Then it would show up like this: https://github.com/cal-andrew/example-repo/tags
