### ISSUE TITLE
Switching Difficulty discord

### ISSUE THREAD

**Issue by DreymaR** [ColemakMods/mod-dh#9]
On your [Switching Difficulty](http://colemakmods.github.io/mod-dh/learn.html) page you claim that moving common letters is extremely disruptive and moving rare letters minimally impacting.

As you know, we've discussed this and there's discord on the subject. While your statements may be correct immediately after switching, in my experience they are grossly incorrect after only a few days. Moving a common letter creates a ruckus but since it's so common you get to train and focus on it a lot and so it's quickly relearnt. Add to that the fact that common letters are generally moved to better positions (or else what's the point in moving them?!), which makes their transitions even easier.

In contrast, it's the rare letters that keep tripping me up a long time after a switch, disrupting the flow of typing. It's my firm belief that the total disruption caused by rare keys is in fact bigger than that caused by the common keys that go to better positions!

My hypothesis is supported by my own observations, lately during my two Curl(DH)-mod switches. The D and H fell quickly into ranks. while the V, M and K caused trouble long thereafter.

This is an enheartening thought for Colemak, which moves many good keys to better positions and often keeps less essential keys such as QWZXCV in their poorer QWERTY positions.

I'm hoping that you'll revise your page. If you don't want to rework your thoughts and model, at least let your page show the above dissent to some extent in the name of good typing science! ;-)

**Comment by stevep99** [comment]
This page does need some work, the switching difficultly model described is not entirely satisfactory, but it is at least caveated. I recognise your argument that more frequent letters can be learned more quickly. However I do still think switching a higher frequency letter creates a disproportionately larger disruptive effect, especially in short term, which ought to be captured by the algorithm in some way.

The table does at least show the "Keys Moved Index", which effectively the "switching difficulty" if you don't include the letter frequency.

This page has been due for an update for a while, so I will revise it along the lines you suggest.

**Comment by stevep99** [comment]
I have developed a new model for the "switching difficulty" on this page, in which the impact of key frequency is reduced. I also now mention the influence of use of key frequency is debatable.
