### ISSUE TITLE
Where is the source code for the analyzer ?

### ISSUE THREAD

**Issue by Nuclear-Squid** [ColemakMods/mod-dh#93]
I wanted to see how your analyzer worked, and when checking your repo it seems most of the code is in a [minified js file](https://github.com/ColemakMods/mod-dh/blob/8fc0e0e3ba070ebf75dfce2f7682aae555157358/webapp/teavm/classes.js) with no human-readable sources. The folder it’s found in shares the name of a java to JS compiler, so I was expecting to find a Java source file but couldn’t. Am I missing something ?

**Comment by stevep99** [comment]
The analyzer tool is in a separate project:
https://github.com/stevep99/keyboard-layout-analysis-tool
